version: "3.4"

services:
  apache:
    image: httpd:2.4
    volumes:
      - ${VOLUME_DIR}:/var/www/html
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${VOLUME_DIR}:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./sslNew/:/etc/nginx/certs
    depends_on:
      - apache

  php:
    container_name: home_dev_php
    build:
      context: ./images/php/${ENV_PHP_V}
      args:
        environment: development
    volumes:
      - ${VOLUME_DIR}:/var/www/html
    user: ${CURRENT_UID}
    environment:
      - XDEBUG_CONFIG=discover_client_host=true start_with_request=yes client_host=${LOCAL_IP:-localhost} xdebug.log=/tmp/xdebug.log
      - XDEBUG_MODE=develop,debug
      - XDEBUG_SESSION=1

  rg_mysql:
    image: biarms/mysql:5.7
    ports:
      - 3347:3306
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    links:
      - rg_mysql:mysql_db_server
    ports:
      - 8080:80

