version: '3'

services:
  apache:
    image: httpd:2.4
    volumes:
      - ${VOLUME_DIR}:/var/www/html
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php
    networks:
      - static-network

  nginx:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ${VOLUME_DIR}:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - apache
    networks:
      - static-network

  php:
    build:
      context: ./images/php
    volumes:
      - ${VOLUME_DIR}:/var/www/html
    user: ${CURRENT_UID}
    networks:
      - static-network

  rg_mysql:
    image: mysql:5.7
    ports:
      - 3347:3306
    depends_on:
      - php
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      - static-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    links:
      - rg_mysql:mysql_db_server
    ports:
      - 8080:80
    networks:
      - static-network

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.123.0.0/16
